### ISSUE TITLE
Framework for generating achievements

### ISSUE THREAD

**Issue by jamesremuscat** [jamesremuscat/TNTFL-web#2]
We'd like to have "achievements" which can be awarded to players at certain times. For example, achieving a ten-game winning streak, or 10-0ing a new player, or... etc.

**Comment by moreginger** [comment]
- Flawless victory: 10-0
- Mostly harmless: 100 games
- Dangerous: 1000 games
- Elite: 10000 games
- Against the odds: Beat an opponent ranked 50 ELO higher (after first 20 games for both players)
- Dedication: 1 year continously ranked (no 60-day gap)
- The Best: Obtain top ranking
- The Worst: Obtain lowest ranking
- Improver: Career ELO min-max of 100 (in that order, can't just lose 100 ELO!)
- Unstable: ELO delta of 10 in opposing directions in two consecutive games
- Comrades: Play 100 games against a single opponent

**Comment by nicolas-duvauchel** [comment]
Would love to have weekly achievements such as player with the
- most points gained/lost
- most places gained/lost
- best/worst avg score/game
- highest/smallest points exchange (Σabs(player_game_points))

**Comment by jamesremuscat** [comment]
Hmm, time-based achievements are difficult (since everything is event-driven there's no way to automatically do things after a week etc) - worth its own issue.

**Comment by moreginger** [comment]
~~Did you mean to close this?~~
Whoops I guess you did, I blame mobile UI :)
