### ISSUE TITLE
Auto-Punditry

### ISSUE THREAD

**Issue by ashirley** [jamesremuscat/TNTFL-web#3]
Similar to the achievements system in issue #1.

It should be possible to produce a pundit style comment for any given game.

Examples might include:
- That game featured abc's 3000th goal
- That was abc's 2000th game
- With a points change of 12.34, that was the 7th most significant game ever.
- With a points change of 12.34, that was the most significant game since 3rd April (18 weeks ago).
- After 34 games between them, that was the first time abc has lost to def.
- abc now has a winning streak of 7, their highest since 3rd April (18 weeks ago).
- That game puts abc on their highest ever points.
- That game puts abc on their highest points since 3rd April (18 weeks ago).

**Comment by jamesremuscat** [comment]
Someone implemented this at some point :)
